export const FETCH_NATIONAL_DATA = 'FETCH_NATIONAL_DATA';
export type FETCH_NATIONAL_DATA = typeof FETCH_NATIONAL_DATA;

export const RECEIVE_NATIONAL_DATA = 'RECEIVE_NATIONAL_DATA';
export type RECEIVE_NATIONAL_DATA = typeof RECEIVE_NATIONAL_DATA;